# This is a basic workflow to help you get started with Actions

name: Precommit check and test build

# Controls when the action will run. 
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Say Hello!
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Typo CI - Spellcheck Action
        uses: TypoCI/spellcheck-action@v0.3.0
        
      - name: pipeline-components-markdown-spellcheck
        uses: pipeline-components/markdown-spellcheck@v0.6.0
        with:
          # Directory to lint
          directory: _posts/*.md # optional, default is **/*.md
