# This is a basic workflow to help you get started with Actions

name: Precommit check and test build

# Controls when the action will run. 
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
    
      - name: install ruamel
        run: pip install ruamel_yaml
      
      - name: Configuring Git
        run: |
          git config --global user.name 'keep the floyd'
          git config --global user.email 'keepfloyding@users.noreply.github.com'
        
      - name: Run init.sh
        run: ./init.sh

      # Runs a single command using the runners shell
      - name: Say Hello!
        run: echo Hello, world!
      
      - name: Install ruby tools
        run: sudo apt-get install ruby-full build-essential zlib1g-dev
    
      - name: Install Jekyll and bundler
        run: sudo gem install jekyll bundler

      - name: Install gems
        run: sudo bundle install
     
      - name: Run init.sh
        run: ./init.sh
      
      - name: Perform one-off build of jekyll
        run: bundle exec jekyll build
      
      - name: Add/commit changes to changed files
        run: |
          git add tags/
          git add categories/
          git commit -am "Automated report"
          git push
        
       
          
